// Builds the example project ("Electrocatalysis Must-Reads") from scripts/catalogue-source.js:
//   src/example.js      – bundled into the site so guests can browse it without signing in
//   supabase/seed.sql   – the same project and papers, with the same ids, for the database
// Ids are derived from titles, so re-running keeps everyone's reading progress attached.
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { RINGS, FIRST, PAPERS } from "./catalogue-source.js";

const uuid = s => {
  const h = createHash("sha1").update("reading-rings:" + s).digest("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-5${h.slice(13, 16)}-${((parseInt(h[16], 16) & 3) | 8).toString(16)}${h.slice(17, 20)}-${h.slice(20, 32)}`;
};
const PROJECT_ID = "00000000-0000-4000-8000-000000000001";
const sections = RINGS.map(r => ({ id: r.id, name: r.name, sub: r.sub, blurb: r.blurb }));
const papers = PAPERS.map((p, i) => ({
  id: uuid(p.t), project_id: PROJECT_ID, title: p.t, authors: p.a || "", journal: p.j || "", year: p.y || null,
  doi: p.d || null, section: p.r, topic: p.g || "", note: p.w || "", essential: !!p.e, position: i,
}));
const byTitle = new Map(papers.map(p => [p.title, p.id]));
const project = {
  id: PROJECT_ID, name: "Electrocatalysis Must-Reads", is_template: true,
  description: "196 papers in six rings, from the foundations every catalysis field shares out to the frontier of electrocatalysis. Start with the 14-paper first pass, then read each ring from the centre out, starred papers first.",
  sections, meta: { firstPass: FIRST.map(t => byTitle.get(t)).filter(Boolean) },
};
writeFileSync("src/example.js", `// Generated by scripts/make-example.mjs. Edit scripts/catalogue-source.js instead.
export const EXAMPLE_PROJECT = ${JSON.stringify(project)};
export const EXAMPLE_PAPERS = ${JSON.stringify(papers).replace(/\},\{/g, "},\n{")};
`);
const q = v => v === null || v === undefined ? "null" : typeof v === "number" || typeof v === "boolean" ? String(v) : "'" + String(v).replace(/'/g, "''") + "'";
let sql = `-- Generated by scripts/make-example.mjs. Run after schema.sql. Safe to re-run.
insert into public.projects (id, owner, name, description, sections, meta, is_template)
values (${q(PROJECT_ID)}, null, ${q(project.name)}, ${q(project.description)}, ${q(JSON.stringify(sections))}::jsonb, ${q(JSON.stringify(project.meta))}::jsonb, true)
on conflict (id) do update set name = excluded.name, description = excluded.description, sections = excluded.sections, meta = excluded.meta;

insert into public.papers (id, project_id, owner, title, authors, journal, year, doi, section, topic, note, essential, position) values
`;
sql += papers.map(p => `(${[p.id, p.project_id].map(q).join(", ")}, null, ${[p.title, p.authors, p.journal, p.year, p.doi, p.section, p.topic, p.note, p.essential, p.position].map(q).join(", ")})`).join(",\n");
sql += `
on conflict (id) do update set title = excluded.title, authors = excluded.authors, journal = excluded.journal, year = excluded.year,
  doi = excluded.doi, section = excluded.section, topic = excluded.topic, note = excluded.note, essential = excluded.essential, position = excluded.position;
`;
writeFileSync("supabase/seed.sql", sql);
console.log("example papers:", papers.length, "unique ids:", new Set(papers.map(p => p.id)).size, "first pass:", project.meta.firstPass.length);
